---
about:
  template: jolla
  id: about-block
  image: "" # personal image here
  links:
    - icon: github
      text: Github
      href: https://github.com/zvkong
    - icon: linkedin
      text: LinkedIn
      href: https://www.linkedin.com/in/zewei-kong-229b951ab
    - icon: envelope
      text: Email
      href: "mailto:kongz@missouri.edu"
---

::: {#about-block}
:::

# Welcome to My Website
Welcome to my personal website! I am Zewei Kong, a Ph.D. candidate at the University of Missouri.

As a statistical researcher, I am dedicated to exploring Bayesian methodology and its applications in complex data structures. My doctoral research focuses on multi-type models for small area estimation within the context of survey data. Specifically, I am currently proposed and validated a novel Bayesian hierarchical framework for the joint modeling of Gaussian and binomial data.

Beyond a solid theoretical foundation in Bayesian hierarchical modeling and small area estimation, I possess strong skills in statistical programming, data processing, and visualization. Proficient in R and Python, I can independently manage the entire process from model construction to final result presentation.

Furthermore, I have a strong interest in Machine Learning and exploring the intersection of Artificial Intelligence with traditional statistical methods. For instance, I developed TraffIQ, an interactive map-based web application built with RShiny. This project successfully integrates complex statistical analyses with an AI backend, delivering data-driven insights to users through an intuitive and user-friendly UI/UX design.

If you are interested in Bayesian modeling, Machine Learning, data analytics, or my specific research areas, please feel free to [contact me](mailto:kongz@missouri.edu). I am always open to connecting with fellow researchers and developers.

```{=html}
<div  style="margin: 30px; text-align: center;">
<a class="btn btn-primary" href="cv/index.qmd" role="button" style="padding: 15px 30px;">View My CV</a>
</div>
---